language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - LANG=en_US.UTF-8
matrix:
  include:
    - env:
        - TOXENV=check
      python: '3.8'
    - env:
        - TOXENV=py36,codecov
      python: '3.6'
    - env:
        - TOXENV=py37,codecov
      python: '3.7'
    - env:
        - TOXENV=py38,codecov
      python: '3.8'
    - env:
        - TOXENV=pypy3,codecov
        - TOXPYTHON=pypy3
      python: 'pypy3'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_success:
    - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*
deploy:
  provider: pypi
  user: "__token__"
  password:
      secure: "R6/aAbLVro9AlQ6z1roGSosY4VykZYw0Qf7fyVz1NJ1X/xdBiWLDorSEljcy0HQARNTuKOC93FLXXWUz3tC7eCv43qpsdNNL+hUWUe4XQmaNxRxTtlofCcjD/ypYF9t95dsY/i9YQvbFpYA3zrcqUiJGGrJH/Wms31giOfz4i01rSS6aGEf2wjHEqnDhtiHlLIs96PacVqggPFFyQEqaUX5btJX1Nb/qFSE5ZBIGZyuhZJo2jSf8XuQqUAwI8PeUPS4CVrgN2FuAUfhyYcLF7b0cADxCqFtW7ItGW+gC8ryBbGFci0y7PA1wDaTfY42a7AOo8N2M+ofjIbIhzMyRUPuuhSqQ8qQte2MhNuKpYkOWh1m58fkND7J+7u1TK4VMLDq2GcG9yxkTymJuurSOMo0hCp2k+hhH++epRwMuHDyY065ibIhAxgtU8DGUYLGo2Re6zzq6SLfb3QpZUridGYHxlkqLj/oNW8Hl/mdHphbYtVgS2apPjwqSVnLigUq9uSkc+jmVexY7oeLzDoByWPqteu9V+oQAcKt7dowEGRsWXmxAkSdPZKEUskIkSlTmO5+y5wYE9Bx7cqMJ6Rz1qNPzP+pTMdjBl1uyxZmhRZI1fnmJ9wxY2xgNQsb5KEjQCKtUoWXBcFtVgxSy43E0IqOHvj/EijP0jFMPeakW1Bw="
  on:
      tags: true
      python: 3.8
  distributions: "sdist bdist_wheel"
  skip_existing: true
notifications:
  email:
    on_success: always
    on_failure: always
