language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - LANG=en_US.UTF-8
matrix:
  include:
    - env:
        - TOXENV=check
      python: '3.8'
    - env:
        - TOXENV=py36,codecov
      python: '3.6'
    - env:
        - TOXENV=py37,codecov
      python: '3.7'
    - env:
        - TOXENV=py38,codecov
      python: '3.8'
    - env:
        - TOXENV=pypy3,codecov
        - TOXPYTHON=pypy3
      python: 'pypy3'
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_success:
    - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat .tox/log/*
  - cat .tox/*/log/*
deploy:
  provider: pypi
  user: "__token__"
  password:
      secure: "fn3GTrMpVAydw/XZfcRYLmQUAAYyOgZHGhR8q0zNt1vEbuH1Yi9WqfWuUZdDA5+WwvvKfW5Lcxxn0sSkkaYtGGXMKlu5vmWl4ujrD7FFzP+W6L7yiCPqUZppy2uCrigwZgt1ODbzGHXexi5PYshe2rnq19cloG7k4npOAgs2bj3cPaQsPLpoPl2Xd7hhSDVVPgKRU+qQ/Y3jMoLVfis8eatdMJiAb1cBdzPuY2mG9WST1dKWYXKtn7Kg6s89Cehy3mXcOC8ILw5yYTOifDPkgT7B4M5gYFXjkQfW+cva31z2iEo1qUvINzKDPgmViVgaeFDCJpwGjjOg4DZgrWA80N6tsjVvPZBxf1sAmuYmo2TnQ54OSrocz9DhQV/h4jHqyyY16FdljxtumIfJJqZgAclZdAFdrqybnAsqTP8q5ravJXlyk9f6Xs7cx1s5i/hz/B81gYG/MbwN/qpLo1r450LYgy3GnjsCPXmTdDsypDbPYknMG9r/QoSrAiKdHmm6Ayeblwws8+sVfX8grpZQOo6c3sP8g6vHkny3GJVfaitEwz7/welLQm1AH++fnEHDST2f7XZRn2C7I84FkaeW3gyhcxyX2YzVgV7THIRd8YwNwMNDAD+hUFCEaPY+eDLPYqMiz1TdAW9r7TZUJqRP/hKMoigzgP+j/tFj34sn3mU="
        on:
      tags: true
      python: 3.6
  distributions: "sdist bdist_wheel"
  skip_existing: true
notifications:
  email:
    on_success: always
    on_failure: always
